# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.

baseURL = "https://mariusroger.github.io/"
title = "Marius Roger"
theme = "my-theme"

languageCode = "en-us"
# defaultContentLanguage = "en"

# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT = true
# paginate = 10
summaryLength = 0

buildDrafts = false
buildFuture = false

enableEmoji = true

[imaging]
  anchor = "Center"

[taxonomies]
  tag = "tags"
  category = "categories"

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

# [outputs]
#  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true

